### PR TITLE
Feat: add deploy notification

### LINKED ISSUE #278: Deploy notification
Add an option to configure deploy notification in addition to uploading source maps. Maybe something like this:

```js
const webpackConfig = {
  plugins: [new HoneybadgerSourceMapPlugin({
    apiKey: 'abc123',
    assetsUrl: ASSETS_URL,
    revision: 'master',
    deploy: {
        environment: 'production',
        repository: 'git repo url',
        local_username: 'deploy user'
    }
  })]
}
```

https://docs.honeybadger.io/api/deployments.html

### PR DESCRIPTION
**Pull request by ParamagicDev**
## Status

WIP!!!! Needs to add testing / documentation

Closes #278

## Description

Sends a deploy notification when webpack successfully compiles.

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog Entry (unreleased)

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```bash
> git pull --prune
> git checkout <branch>
> npm test
```

### CODE REVIEW

**Review by joshuap — COMMENTED** [review]
This is looking good to me. 👍

**Comment by Pierre-Do** [comment]
Hey @ParamagicDev , any news on this? If there's a beta published with this feature I'd be happy to give it a go.

**Comment by ParamagicDev** [comment]
@Pierre-Do sorry I've been swamped with work recently. I haven't had a chance to add tests for this, but it _should_ work. As far as I'm aware there's no release for this yet.

**Comment by shalvah** [comment]
Hey @ParamagicDev I've resolved conflicts and added some integration tests for this feature.

**Review by joshuap — COMMENTED** [review]
Thanks @shalvah, looks good to me. Can you update the readme with the new config, and add a changelog entry?

@ParamagicDev do you want to take a look?

**Review by ParamagicDev — COMMENTED** [review]
@shalvah This came out really well! Thank you for picking up the slack and pushing this through! Apologies for not being able to finish this, ive unfortunately been fairly busy recently.

**Comment by shalvah** [comment]
No problem @ParamagicDev .👍

Btw: I noticed your implementation required environment, repository and localUsermame to be present, but [the deployment API](https://docs.honeybadger.io/api/deployments.html) has them as "optional". I assume it was an oversight, so I've made them all optional (you can simply pass `deploy: true` to enable deployment notifications).

**Comment by shalvah** [comment]
> Thanks @shalvah, looks good to me. Can you update the readme with the new config, and add a changelog entry?
> 
> @ParamagicDev do you want to take a look?

Done

**Review by joshuap — APPROVED** [review]
Looks good, thanks to both of you!

**Comment by joshuap** [comment]
@shipjs prepare

**Pull request merged**
