### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by shalvah**
## Status
**READY**

## Description
This PR adds integration tests for the post-compilation process. This allows us to add better tests for the deployment notification feature #307.

### CODE REVIEW

**Comment by shalvah** [comment]
Is there a reason we have our package-lock in Git? CI is having trouble installing the keepachangelog module for some reason. Spent an hour+ trying to fix dependency issues. It's not a very productive use of time, considering these are dev dependencies that end users won't be installing.

(Also, why are we using a custom keepachangelog repo? Doesn't look like there have been any custom changes. It's just making the build harder. If we want to use a specific version, we can simply pin to a commit from the original repo.)

**Comment by joshuap** [comment]
> Is there a reason we have our package-lock in Git? CI is having trouble installing the keepachangelog module for some reason. Spent an hour+ trying to fix dependency issues. It's not a very productive use of time, considering these are dev dependencies that end users won't be installing.

I'm fine with removing the package-lock from Git. I'm not sure when/why it was committed.
 
> (Also, why are we using a custom keepachangelog repo? Doesn't look like there have been any custom changes. It's just making the build harder. If we want to use a specific version, we can simply pin to a commit from the original repo.)

There are changes on the release branch:

https://github.com/honeybadger-io/keepachangelog/tree/release

**Review by joshuap — APPROVED** [review]
Looks OK to me—this doesn't hit the live API, right?

**Comment by shalvah** [comment]
Shit, it actually does. Forgot to mock the endpoint.

Although I should point out—the API returns a 201 success response, even though the test uses a fake API key. Is that by design?

**Comment by shalvah** [comment]
Fixed.

**Comment by shalvah** [comment]
Finally ready.

**Comment by joshuap** [comment]
> Although I should point out—the API returns a 201 success response, even though the test uses a fake API key. Is that by design?

Yeah, that's by design. We have an internal ticket to revisit that in the next API version, though. I wish it returned an error.

**Review by joshuap — APPROVED** [review]
Thanks!

**Comment by shalvah** [comment]
Also also...the `resolvePromisesWithWorkers` doesn't use any workers? 🤨

**Comment by shalvah** [comment]
Based on this comment, it seems what we want to achieve is chunking, maybe?

```
    // On large projects source maps should not all be uploaded at the same time,
    // but in parallel with a reasonable worker count in order to avoid network issues
   
```

**Pull request merged**
